---
# tasks file for instancecreation
- name: instance creation
  ec2:
    key_name: "{{ keypair }}"
    group: "{{ security_group }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    wait: true
    region: "{{ region }}"
    vpc_subnet_id: subnet-5ba42775
    assign_public_ip: yes

